from flask import Flask, request, Response

#import functions  # Required, used in functions with complex scopes that don't handle global vars properly.
#import connection
#import random
#import math
#import geopy.distance
#import datetime  # Required! Handles datetime format in/from queries.
#global questions  # Used in sidequests, DO NOT USE ELSEWHERE!
#global original_questions_list  # Used in sidequests, DO NOT USE ELSEWHERE!

app = Flask(__name__)

# Vars
currentlng = 1  # 1 = English,
playercount = 2  # Number of players.
numofgoals = 4  # Total number of goals generated in game.
goalturntracker = 0
activegoal = 1  # For keeping track of the latest player goal. Input from latestgoallookup()
currentplayer = 1
turncounter = 0  # Tracks in game turn, aka total turns.

# Lists
hintsround0 = ["", "", "", ""]  # For remembering hints generated by hintcreation() func.
hintsround1 = ["", "", "", ""]  # etc etc...
hintsround2 = ["", "", "", ""]
hintsround3 = ["", "", "", ""]
hintsall = [hintsround0, hintsround1, hintsround2, hintsround3]
endscores = []

def cursor(query):
    sqlcursor = connection.sqlconnect.cursor()
    sqlcursor.execute(query)


def cursor_fetchall(query):
    sqlcursor = connection.sqlconnect.cursor()
    sqlcursor.execute(query)
    outcome = sqlcursor.fetchall()
    return outcome

@app.route("/game")
def startmenu(lng):
    if lng == 1:
        startmenuoption = ""
        while True:
            return "3"
            # TODO New colour for these kinds of lists potentially.
            print("[1]New game")
            print("[2]Options")
            print("[3]Credits")
            print("[4]Scoreboard")
            print("[0]Quit")
            try:
                startmenuoption = int(input(f"{BColors.OKCYAN}Enter choice: {BColors.ENDC}"))
            except ValueError:
                print(f"{BColors.CRED2}ERROR!\nInput int from available options.")
            if startmenuoption == 1:
                new_game(lng)
                return
            elif startmenuoption == 2:
                options(lng)
                startmenuoption = input(
                    f"{BColors.OKCYAN}Press enter to go back. {BColors.ENDC}")  # TODO create options.
                if startmenuoption == "":
                    continue
            elif startmenuoption == 3:
                gamecredits(lng)
                startmenuoption = input(f"{BColors.OKCYAN}Press enter to go back. {BColors.ENDC}")
                if startmenuoption == "":
                    continue
            elif startmenuoption == 4:
                scoreboarddisplay()
                startmenuoption = input(f"{BColors.OKCYAN}Press enter to go back. {BColors.ENDC}")
                if startmenuoption == "":
                    continue
            elif startmenuoption == 0:
                print(f"{BColors.OKCYAN}pwease down't weave me :(")
                exit()

























if __name__ == '__main__':
    app.run(use_reloader=True, port=3000)